### ISSUE TITLE
Include can't find file in same directory

### ISSUE THREAD

**Issue by nick-prat** [AtomLinter/linter-clang#196] opened 2017-03-31 17:28 UTC
If you use a .clang_complete project won't be able to find files located in the same directory anymore unless they are in the root project directory.

For example if I have a .clang_complete with `-I./src/` and files

- main.cpp
- src/a.cpp
- src/a.hpp
- src/thing/b.cpp
- src/thing/b.hpp 

then `#include <a.hpp>` and `#include <thing/b.hpp>` works in main.cpp, `#include "a.hpp"` works in a.cpp, but `#include "b.hpp"` fails in b.cpp

**Comment by Arcanemagus** [comment] 2017-03-31 18:21
Have you modified the "Clang Include Paths" setting? That [defaults](https://github.com/AtomLinter/linter-clang/blob/v4.0.0/package.json#L22) to `.` so the current directory _should_ be included. Any flags from `.clang_complete` are merged in after the include paths from that setting so both should be taking effect.

I'll try to reproduce locally though.

**Comment by nick-prat** [comment] 2017-03-31 20:11
Think I found out why it's doing this. If you have a .clang_complete file it seems to report all the includes properly but also reports a `"-working-directory=/home/nick/Programming/C++"` in my test.

Seems like it's accidentally changing the working directory to the root folder. I just tested it and if I have a file c.hpp in the root directory and put `#include "c.hpp"` into src/thing/b.hpp it won't report an error.

**Comment by Arcanemagus** [comment] 2017-03-31 20:30
Oh _bizarre_, this is actually the fault of the `.clang_complete` file, or rather what [`clang-flags`](https://github.com/Kev/clang-flags) gives us in this situation.

When asked for the flags for `b.cpp`, `clang-flags` returns:
```js
[
  "-I./src/",
  "-working-directory=C:\Temp\github\linter-clang_GH196"
]
```
_(`C:\Temp\github\linter-clang_GH196` is the directory of the `.clang_complete` file)_

This seems to be causing `clang` to work as if `C:\Temp\github\linter-clang_GH196` is the base directory, even though it is being ran from `C:\Temp\github\linter-clang_GH196\src\thing`. 

So it looks like this is a duplicate of https://github.com/Kev/clang-flags/issues/11, for now as a work around it looks like you'll  need to add `-I./src/thing/` to the `.clang-complete` file.

**Comment by nick-prat** [comment] 2017-03-31 22:10
So I did some further testing, and I don't think this is an external problem. It seems like -working-directory is needed to show where the -I includes are located. I believe the problem is that you're passing via stdin, which makes it so clang won't know what subdirectory to search for the local includes.

Changing

```javascript
args.push('-');

const execOpts = {
  stdin: fileText,
  stream: 'stderr',
  allowEmptyStderr: true,
  cwd: fileDir,
};
```

to

```javascript
args.push(filePath);

const execOpts = {
  stream: 'stderr',
  allowEmptyStderr: true,
};
```

will fix this problem.

**Comment by Arcanemagus** [comment] 2017-04-01 07:42
Uggg, I assumed `.clang-complete` configuration files were per-directory as the previous documentation I read just mentioned how "easy to programmatically generate" they are, but what looks to be the [original docs](https://github.com/Rip-Rip/clang_complete#minimum-configuration) state that it is only intended to be the project root.

It sounds like when a `.clang-complete` file is in use I'll have to disable linting of the editor contents.

**Closed** 2017-04-01 08:08 UTC
Labels: External

**Comment by Arcanemagus** [comment] 2017-04-01 08:13
v4.1.0 is released including these changes. 🎉
