### ISSUE TITLE
Linter not working.

### ISSUE THREAD

**Issue by horcrux2301** [AtomLinter/linter-clang#202] opened 2017-04-02 08:47 UTC
I am trying to make a cpp file and even when I type gibberish the linter shows me no errors.

I have linter(2.1.2), linter-clang(4.1.0) and linter ui-default(1.2.2) installed. I am using MacOS. Can anybody please help me in fixing this?

**Comment by NanerLee** [comment] 2017-04-02 10:58
+1

**Comment by horcrux2301** [comment] 2017-04-02 11:09
Someone suggested me to install the version 4.0.0 in another thread and it seems to work fine for now. @NanerLee

**Comment by TrovatelliT** [comment] 2017-04-03 07:27
Same of me on mac with and in C

**Comment by diegoferigo** [comment] 2017-04-03 13:12
+1 on Ubuntu 16.10 and v4.1.0

**Comment by Arcanemagus** [comment] 2017-04-03 16:01
Closing as a duplicate of #199.

**Closed by Arcanemagus** 2017-04-03 16:01 UTC
Labels: duplicate
