### ISSUE TITLE
Error: Process Execution Timed out

### ISSUE THREAD

**Issue by ChrisJefferson** [AtomLinter/linter-clang#148] opened 2016-04-22 12:44 UTC
I keep getting the following error box appear:

```
Error: Process execution timed out
    at /Users/caj/.atom/packages/linter-clang/node_modules/atom-linter/lib/helpers.js:79:18
```

Weirdly, this happens when I don't have any C/C++ files open (I'm currently editing latex)

**Comment by Arcanemagus** [comment] 2016-04-22 18:26
Closing as a duplicate of https://github.com/steelbrain/atom-linter/issues/130.

**Closed by Arcanemagus** 2016-04-22 18:26 UTC
