### ISSUE TITLE
Live Linting

### ISSUE THREAD

**Issue by 7CTech** [AtomLinter/linter-clang#180] opened 2017-01-29 08:20 UTC
Would it be possible to introduce live linting? Looking through the code, you tell clang to open a file. If you pipe the contents of the file into clang and then put a dash, you have the same effect. ie. "*insert content here*" | clang -

Alternatively, you could backpipe: clang - < <("*instert contents here*")

**Comment by Arcanemagus** [comment] 2017-01-31 00:52
Duplicate of #119.

**Closed by Arcanemagus** 2017-01-31 00:52 UTC
