### ISSUE TITLE
Linter does not work

### ISSUE THREAD

**Issue by vlasenkov** [AtomLinter/linter-clang#200] opened 2017-04-01 13:09 UTC
Linter-clang does not work. Atom opens without problems, no error messages. In dev tools I found:

```
Uncaught Error: write EPIPE          events.js:160

Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError
```

Launching from terminal didn't help. Adding to init script things like `process.env.PATH = ["/usr/local/bin", process.env.PATH].join(":")` too.

Atom 1.15.0
linter-clang 4.1.0
linter 2.1.2
macOS 10.12.1

**Comment by steelbrain** [comment] 2017-04-01 13:19
Hi @vlasenkov

Can you tell us what shell you're using and what does your shell config look like?

**Comment by vlasenkov** [comment] 2017-04-01 13:22
Hi, @steelbrain 
```
$ echo $SHELL
/bin/bash
```
`~/.bashrc` is empty

**Comment by steelbrain** [comment] 2017-04-01 13:23
If you are on macOS, you're more than likely to have a `~/.bash_profile`, what does it look like?

**Comment by vlasenkov** [comment] 2017-04-01 13:24
```
# added by Anaconda2 4.1.1 installer
export PATH="/Users/leonidvlasenkov/anaconda/bin:$PATH"
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# added by Anaconda3 4.1.1 installer
export PATH="/Users/leonidvlasenkov/anaconda/bin:$PATH"
alias ls='ls -GF'
export CLICOLOR=1
```

**Comment by steelbrain** [comment] 2017-04-01 13:27
Can you try this in your Dev console and show us what you see? (View -> Developer -> Toggle Developer Tools)
```
require(process.env.HOME + '/.atom/packages/linter-clang/node_modules/atom-linter').exec('bash', ['-c', "echo $PATH"]).then(function(result) {
  console.log('result', result)
}).catch(e => console.error(e))
```

**Comment by vlasenkov** [comment] 2017-04-01 13:29
<img width="668" alt="screen shot 2017-04-01 at 16 28 17" src="https://cloud.githubusercontent.com/assets/13369474/24579147/4ce65bec-16f8-11e7-9b28-f5a00a0f6c1b.png">

**Comment by steelbrain** [comment] 2017-04-01 13:31
I feel like we should do this on Slack maybe haha, so much back and forth debugging. Anyway can you see if this `$PATH` value is different from the one you get by doing `echo $PATH` in your terminal if it is, what's the terminal value?

**Comment by vlasenkov** [comment] 2017-04-01 13:33
This is $PATH:
`/Users/leonidvlasenkov/anaconda/bin:/Users/leonidvlasenkov/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin`

**Comment by steelbrain** [comment] 2017-04-01 13:34
It just looks like a shell inconsistency if I had to guess, moving over the contents from `~/.bash_profile` to `~/.bashrc` should fix it (or was it vice-versa? :D)

**Comment by vlasenkov** [comment] 2017-04-01 13:40
Unfortunately nothing changed after `mv .bash_profile .bashrc`

**Comment by vlasenkov** [comment] 2017-04-01 13:42
I noticed that when I run Atom from terminal it opens no files. But when I run Atom from Applications folder it reopens last edited items

**Comment by db47h** [comment] 2017-04-01 13:48
Same problem for me on Ubuntu 16.04. 

After deliberately creating errors, I see outpout in the console, for example: 

> <stdin>:46:10: error: out-of-line definition of 'Touch' does not match any declaration in 'UI'
> void UI::Touch(double x, double y, int action) {
>         ^~~~~
>
> clang-provider.coffee [sm]:45 1 error generated.

But the linter-ui doesn't get updated. This happens since v4.1.0.

**Comment by nick-prat** [comment] 2017-04-01 16:36
Check to see if it's not linting because of this error #199. I'm on ubuntu as well and had to comment out this flag to make it work again

**Comment by Arcanemagus** [comment] 2017-04-01 17:43
@db47h Are you getting the _exact_ same error trace as in the first comment? If not, please file a new issue.

@nick-prat this is definitely not the same issue. Your issue in #199 is due to using an out of date `clang`.

**Comment by Arcanemagus** [comment] 2017-04-01 17:50
@db47h Your message you posted above seems to be coming from [autocomplete-clang](https://github.com/yasuyuky/autocomplete-clang/blob/198f05c75c82527978d7510449315791ec96094a/lib/clang-provider.coffee), are you sure that `linter-clang` is the problem?

**Comment by db47h** [comment] 2017-04-01 21:31
@nick-prat thanks, that was it!

Indeed, that message was coming from autocomplete-clang. linter-clang just doesn't seem to be working with no error message at all (so yes, the issue I'm having is #199).

**Comment by Damowerko** [comment] 2017-04-01 22:00
I am having the same problem as @vlasenkov. Everything was working until I updated autocomplete-clang. After that the linter stopped flagging errors, except for #include statements - it flagged every single one. Then I updated linter-clang and I get exactly the same error message as @vlasenkov and the ui does not update.

**Comment by Kael-Chan** [comment] 2017-04-02 08:08
same issue on ubuntu16.04,
with clang3.8 and all packages related updated.

now I'm using linter-gcc for a while, though clang is better.

what can I do for it or what information of mine do you want?

**Comment by horcrux2301** [comment] 2017-04-02 09:32
Anybody found a fix yet?

**Comment by ooJerryLeeoo** [comment] 2017-04-02 09:44
`apm install linter-clang@4.0.0`

**Comment by horcrux2301** [comment] 2017-04-02 09:52
@ooJerryLeeoo Thank you.!!!

**Comment by Arcanemagus** [comment] 2017-04-03 16:00
Closing as a duplicate of #199 as it seems the odd error initially posted here is simply a side effect of that problem, and the other issue in this thread is from `autocomplete-clang`.

**Closed by Arcanemagus** 2017-04-03 16:00 UTC
Labels: duplicate

**Comment by Arcanemagus** [comment] 2017-04-03 17:32
v4.1.1 is published which should fix this package for `clang` versions below v4.0.0.

**Comment by horcrux2301** [comment] 2017-04-03 17:36
I updated to v4.1.1 and everything is resolved for me. Thank you.! @Arcanemagus

**Comment by Kael-Chan** [comment] 2017-04-04 07:11
Thank you !
 
 
------------------ Original ------------------

**Comment by vlasenkov** [comment] 2017-04-05 07:22
The problem is still here. I got this at the console:
```Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError```
