### ISSUE TITLE
Deprecated selector in `linter-clang\styles\linter-clang.less`

### ISSUE THREAD

**Issue by ILOFI** [AtomLinter/linter-clang#174] opened 2017-01-15 08:52 UTC
In `linter-clang\styles\linter-clang.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .linter-highlight.fatal-error,
.linter-highlight.fatal-error` => `atom-text-editor.editor .linter-highlight.fatal-error,
.linter-highlight.fatal-error`

* `atom-text-editor::shadow .linter-highlight.fatal-error:not(.line-number),
.linter-highlight.fatal-error:not(.line-number)` => `atom-text-editor.editor .linter-highlight.fatal-error:not(.line-number),
.linter-highlight.fatal-error:not(.line-number)`

* `atom-text-editor::shadow .linter-highlight.fatal-error .linter-gutter,
.linter-highlight.fatal-error .linter-gutter` => `atom-text-editor.editor .linter-highlight.fatal-error .linter-gutter,
.linter-highlight.fatal-error .linter-gutter`

* `atom-text-editor::shadow .linter-highlight.fatal-error .region,
.linter-highlight.fatal-error .region` => `atom-text-editor.editor .linter-highlight.fatal-error .region,
.linter-highlight.fatal-error .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by Arcanemagus** [comment] 2017-01-17 23:35
Duplicate of #171.

**Closed by Arcanemagus** 2017-01-17 23:35 UTC
