### ISSUE TITLE
linter-clang runs, but doesn't mark up buffer

### ISSUE THREAD

**Issue by phaistos** [AtomLinter/linter-clang#92] opened 2015-07-11 03:00 UTC
When I edit C code with the clang linter enabled, I see the plugin working, but it doesn't mark up the buffer with the errors. More specifically it marks the file up one time, and then doesn't work again until I restart Atom or reload.

In developer mode I can see the linter running, it just doesn't update the GUI. I included  a screenshot.
![linter-clang-bug](https://cloud.githubusercontent.com/assets/4316478/8632043/74e20e76-2757-11e5-8588-a9f58d40a1b5.PNG)

linter-clang:2.26.1
Atom:1.0.2
Windows 8.1 
LLVM:3.6.1

**Comment by Kamairo** [comment] 2015-07-12 16:01
Probably a duplicate of my issue #91 .

**Comment by phaistos** [comment] 2015-07-12 18:51
Possibly, wasn't sure if your linter just wasn't running at all. Mine runs, the clang results just don't affect the buffer visually.

**Comment by k2b6s9j** [comment] 2015-08-02 02:44
Please test this with the latest version.

**Comment by k2b6s9j** [comment] 2015-08-11 06:48
Seeing as this issue has grown stale and the linter has since been rewritten I am closing this issue. If it is still occurring please reopen this issue.

**Comment by Wolftein** [comment] 2015-11-25 21:22
Just download this plug-in and i'm having the same issue.

**Comment by t0nyt93** [comment] 2016-06-30 00:33
Any news on this? Having the same exact issue with..

**Comment by don11995** [comment] 2016-08-14 17:58
Same bug here. Running it on Windows 10 64-bit.

**Comment by Arcanemagus** [comment] 2016-08-15 23:19
If you open Atom's Developer Tools and place a breakpoint [here](https://github.com/AtomLinter/linter-clang/blob/v3.4.4/lib/main.js#L119), what is the raw contents of `output`?

**Comment by keplersj** [comment] 2016-08-16 02:42
I suspect that the version of Clang for Windows being used in these instances is not working with the regex.

**Comment by don11995** [comment] 2016-08-16 06:37
The problem was that Atom linter was not installed. I don't know why, but after that Clang linter is working as expected now.

**Closed** 2016-08-16 06:38 UTC
Labels: bug, unconfirmed
